const mysql = require('../Backend/node_modules/mysql2/promise');
const { Client } = require('../Backend/node_modules/pg');

const mysqlUrl = process.env.MYSQL_URL;
const postgresUrl = process.env.DATABASE_URL_UNPOOLED || process.env.NEON_URL || process.env.DATABASE_URL;

if (!mysqlUrl || !postgresUrl) {
  throw new Error('Set MYSQL_URL and NEON_URL (or DATABASE_URL) before running this script.');
}

function postgresType(column) {
  const type = column.Type.toLowerCase();
  if (type.includes('tinyint(1)')) return 'smallint';
  if (type.includes('bigint')) return 'bigint';
  if (type.includes('int')) return 'integer';
  if (type.includes('double') || type.includes('float')) return 'double precision';
  if (type.includes('decimal') || type.includes('numeric')) return type.replace(/unsigned/g, '').trim();
  if (type.includes('json')) return 'jsonb';
  if (type.includes('blob')) return 'bytea';
  if (type.includes('date') && !type.includes('datetime')) return 'date';
  if (type.includes('datetime') || type.includes('timestamp')) return 'timestamp';
  if (type.includes('text')) return 'text';
  const varchar = type.match(/varchar\((\d+)\)/);
  return varchar ? `varchar(${varchar[1]})` : 'text';
}

function defaultValue(column) {
  if (column.Default === null || column.Default === undefined) return '';
  const value = String(column.Default);
  if (/^current_timestamp(?:\(\))?$/i.test(value)) return ' DEFAULT CURRENT_TIMESTAMP';
  if (/^(true|false)$/i.test(value)) return ` DEFAULT ${value.toLowerCase()}`;
  if (/^-?\d+(?:\.\d+)?$/.test(value)) return ` DEFAULT ${value}`;
  return ` DEFAULT '${value.replace(/'/g, "''")}'`;
}

function quoteIdentifier(identifier) {
  return `"${identifier.replace(/"/g, '""')}"`;
}

async function main() {
  console.log('Connecting to MySQL source...');
  const sourceUrl = new URL(mysqlUrl);
  const source = await mysql.createConnection({
    host: sourceUrl.hostname,
    port: Number(sourceUrl.port || 3306),
    user: decodeURIComponent(sourceUrl.username),
    password: decodeURIComponent(sourceUrl.password),
    database: decodeURIComponent(sourceUrl.pathname.slice(1)),
    connectTimeout: 15000,
    ssl: { rejectUnauthorized: false }
  });
  console.log('MySQL source connected. Connecting to PostgreSQL target...');
  const targetUrl = new URL(postgresUrl);
  const isLocalSocket = !targetUrl.hostname;
  const target = new Client({
    host: isLocalSocket ? '/var/run/postgresql' : targetUrl.hostname,
    port: Number(targetUrl.port || 5432),
    user: decodeURIComponent(targetUrl.username) || process.env.USER,
    password: targetUrl.password ? decodeURIComponent(targetUrl.password) : undefined,
    database: decodeURIComponent(targetUrl.pathname.slice(1)),
    family: 4,
    connectionTimeoutMillis: 15000,
    ssl: isLocalSocket ? false : { rejectUnauthorized: false }
  });
  await target.connect();
  console.log('PostgreSQL target connected. Starting migration...');

  try {
    const [tables] = await source.query('SHOW TABLES');
    const tableKey = Object.keys(tables[0] || {})[0];
    const tableNames = tables.map((table) => table[tableKey]);

    for (const tableName of tableNames) {
      const safeTable = quoteIdentifier(tableName);
      const [columns] = await source.query(`SHOW COLUMNS FROM ${safeTable.replace(/"/g, '`')}`);
      const definitions = columns.map((column) => {
        const identity = column.Extra.toLowerCase().includes('auto_increment')
          ? ' GENERATED BY DEFAULT AS IDENTITY'
          : '';
        const nullable = column.Null === 'NO' ? ' NOT NULL' : '';
        return `${quoteIdentifier(column.Field)} ${postgresType(column)}${identity}${nullable}${defaultValue(column)}`;
      });
      const primary = columns.filter((column) => column.Key === 'PRI').map((column) => quoteIdentifier(column.Field));
      if (primary.length) definitions.push(`PRIMARY KEY (${primary.join(', ')})`);

      await target.query(`CREATE TABLE IF NOT EXISTS ${safeTable} (${definitions.join(', ')})`);
      const [rows] = await source.query(`SELECT * FROM ${safeTable.replace(/"/g, '`')}`);

      if (rows.length === 0) continue;
      const fields = columns.map((column) => quoteIdentifier(column.Field));
      const values = [];
      const placeholders = rows.map((row, rowIndex) => {
        return fields.map((field, fieldIndex) => {
          values.push(row[columns[fieldIndex].Field]);
          return `$${rowIndex * fields.length + fieldIndex + 1}`;
        }).join(', ');
      });
      await target.query(
        `INSERT INTO ${safeTable} (${fields.join(', ')}) VALUES ${placeholders.map((value) => `(${value})`).join(', ')} ON CONFLICT DO NOTHING`,
        values
      );
      console.log(`Migrated ${tableName}: ${rows.length} row(s)`);
    }
  } finally {
    await source.end();
    await target.end();
  }
}

main().catch((error) => {
  console.error('Migration failed:', {
    message: error.message,
    code: error.code,
    detail: error.detail,
    severity: error.severity,
    syscall: error.syscall,
    address: error.address,
    port: error.port
  });
  process.exitCode = 1;
});